/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JLabel;

/**
 *
 * @author mike
 */
public class MessageSucefull extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MessageSucefull.class.getName());

    /**
     * Creates new form MessageSucefull
     */
    public MessageSucefull() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registerExitosoCapacidadLabel = new javax.swing.JLabel();
        registerExitosoPlacaLabel = new javax.swing.JLabel();
        registerExitosoTipoLabel = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messageLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(0, 0, 0));
        messageLabel.setText("Vehiculo registrado exitosamente");
        jPanel1.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bus-driver-51(2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 170));

        registerExitosoCapacidadLabel.setForeground(new java.awt.Color(0, 0, 0));
        registerExitosoCapacidadLabel.setText("Capacidad: ");
        jPanel1.add(registerExitosoCapacidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, -1));

        registerExitosoPlacaLabel.setForeground(new java.awt.Color(0, 0, 0));
        registerExitosoPlacaLabel.setText("Placa: ");
        jPanel1.add(registerExitosoPlacaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, -1));

        registerExitosoTipoLabel.setForeground(new java.awt.Color(0, 0, 0));
        registerExitosoTipoLabel.setText("Tipo: ");
        jPanel1.add(registerExitosoTipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 150, -1));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("OK");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MessageSucefull().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel registerExitosoCapacidadLabel;
    private javax.swing.JLabel registerExitosoPlacaLabel;
    private javax.swing.JLabel registerExitosoTipoLabel;
    // End of variables declaration//GEN-END:variables

    public JLabel getMessageLabel() {
        return messageLabel;
    }

    public void setMessageLabel(JLabel messageLabel) {
        this.messageLabel = messageLabel;
    }

    public JLabel getRegisterExitosoCapacidadLabel() {
        return registerExitosoCapacidadLabel;
    }

    public void setRegisterExitosoCapacidadLabel(JLabel registerExitosoCapacidadLabel) {
        this.registerExitosoCapacidadLabel = registerExitosoCapacidadLabel;
    }

    public JLabel getRegisterExitosoPlacaLabel() {
        return registerExitosoPlacaLabel;
    }

    public void setRegisterExitosoPlacaLabel(JLabel registerExitosoPlacaLabel) {
        this.registerExitosoPlacaLabel = registerExitosoPlacaLabel;
    }

    public JLabel getRegisterExitosoTipoLabel() {
        return registerExitosoTipoLabel;
    }

    public void setRegisterExitosoTipoLabel(JLabel registerExitosoTipoLabel) {
        this.registerExitosoTipoLabel = registerExitosoTipoLabel;
    }

    
}
