/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author mike
 */
public class RegisterVehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterVehiculo.class.getName());

    /**
     * Creates new form RegiterVehiculo
     */
    public RegisterVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        placaLabel = new javax.swing.JLabel();
        placaText = new javax.swing.JTextField();
        separadorPlaca = new javax.swing.JSeparator();
        tipoLabel = new javax.swing.JLabel();
        separadorTipo = new javax.swing.JSeparator();
        tipoText = new javax.swing.JTextField();
        capcidadLabel = new javax.swing.JLabel();
        capacidadText = new javax.swing.JTextField();
        separadorCapacidad = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bannerVehiculo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 430, 490));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DriveLoad");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("REGISTRAR VEHICULOS");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        placaLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        placaLabel.setForeground(new java.awt.Color(0, 0, 0));
        placaLabel.setText("PLACA");
        bg.add(placaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        placaText.setBackground(new java.awt.Color(255, 255, 255));
        placaText.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        placaText.setForeground(new java.awt.Color(153, 153, 153));
        placaText.setText("Ingrese la placa del vehiculo");
        placaText.setBorder(null);
        placaText.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        placaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaTextActionPerformed(evt);
            }
        });
        bg.add(placaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 300, 30));
        bg.add(separadorPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 10));

        tipoLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(0, 0, 0));
        tipoLabel.setText("TIPO");
        bg.add(tipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        bg.add(separadorTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 300, 10));

        tipoText.setBackground(new java.awt.Color(255, 255, 255));
        tipoText.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        tipoText.setForeground(new java.awt.Color(153, 153, 153));
        tipoText.setText("Ingrese el tipo de vehiculo");
        tipoText.setBorder(null);
        tipoText.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        tipoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTextActionPerformed(evt);
            }
        });
        bg.add(tipoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 30));

        capcidadLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        capcidadLabel.setForeground(new java.awt.Color(0, 0, 0));
        capcidadLabel.setText("CAPACIDAD");
        bg.add(capcidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        capacidadText.setBackground(new java.awt.Color(255, 255, 255));
        capacidadText.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        capacidadText.setForeground(new java.awt.Color(153, 153, 153));
        capacidadText.setText("Ingrese la capacidad del vehiculo");
        capacidadText.setBorder(null);
        capacidadText.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        capacidadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadTextActionPerformed(evt);
            }
        });
        bg.add(capacidadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 300, 30));
        bg.add(separadorCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 300, 10));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("ENVIAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 117, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaTextActionPerformed

    private void tipoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTextActionPerformed

    private void capacidadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadTextActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterVehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField capacidadText;
    private javax.swing.JLabel capcidadLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel placaLabel;
    private javax.swing.JTextField placaText;
    private javax.swing.JSeparator separadorCapacidad;
    private javax.swing.JSeparator separadorPlaca;
    private javax.swing.JSeparator separadorTipo;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoText;
    // End of variables declaration//GEN-END:variables

    public JTextField getCapacidadText() {
        return capacidadText;
    }

    public JTextField getPlacaText() {
        return placaText;
    }

    public JTextField getTipoText() {
        return tipoText;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JLabel getCapcidadLabel() {
        return capcidadLabel;
    }

    public JLabel getPlacaLabel() {
        return placaLabel;
    }

    public JLabel getTipoLabel() {
        return tipoLabel;
    }

  



}


