/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.ConductorController;
import Modelo.Vehiculo;
import Controlador.VehiculoController;
import Modelo.Conductor;

/**
 *
 * @author mike
 */
public class VistaIniciar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaIniciar.class.getName());
    
    /**
     * Creates new form VistaIniciar
     */
    public VistaIniciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCConsultar = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnV1 = new javax.swing.JButton();
        btnV2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCConsultar.setBackground(new java.awt.Color(0, 0, 0));
        btnCConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnCConsultar.setText("Consultar");
        btnCConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 150, 40));

        btnC.setBackground(new java.awt.Color(0, 0, 0));
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("Registrar");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 150, 60));

        btnV1.setBackground(new java.awt.Color(0, 0, 0));
        btnV1.setForeground(new java.awt.Color(255, 255, 255));
        btnV1.setText("Registrar");
        btnV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, 60));

        btnV2.setBackground(new java.awt.Color(0, 0, 0));
        btnV2.setForeground(new java.awt.Color(255, 255, 255));
        btnV2.setText("Consultar");
        btnV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnV2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 150, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DriveLoad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion Conductores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Gestion Vehiculos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bus-driver-51(2).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 270, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diversity-84(1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 230, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
         RegisterConductores registerConductor = new RegisterConductores();
        Conductor conductor = new Conductor();
        ConductorController controller = new ConductorController(registerConductor, conductor);
        registerConductor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCActionPerformed

    private void btnCConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCConsultarActionPerformed
        // TODO add your handling code here:
      listaConductores listaConducs = new listaConductores();
        listaConducs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCConsultarActionPerformed

    private void btnV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV1ActionPerformed
        // TODO add your handling code here:
        RegisterVehiculo registerVehiculo = new RegisterVehiculo();
         Vehiculo vehiculo = new Vehiculo();

         VehiculoController controlador = new VehiculoController(registerVehiculo, vehiculo);

         registerVehiculo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnV1ActionPerformed

    private void btnV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnV2ActionPerformed
        // TODO add your handling code here:
        listarVehiculos listaVehiculos = new listarVehiculos();
        listaVehiculos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnV2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaIniciar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCConsultar;
    private javax.swing.JButton btnV1;
    private javax.swing.JButton btnV2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
